-- Create table for prosthetic service items
CREATE TABLE IF NOT EXISTS "prosthetic_service_items" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT REFERENCES "prosthetic_services"(id) ON DELETE CASCADE,
  descricao TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE "prosthetic_service_items" ENABLE ROW LEVEL SECURITY;

-- Create policy
DROP POLICY IF EXISTS "Allow all for authenticated" ON "prosthetic_service_items";
CREATE POLICY "Allow all for authenticated" ON "prosthetic_service_items" FOR ALL TO authenticated USING (true) WITH CHECK (true);
