-- SQL Script to create the database schema and fix RLS policies
-- Run this in your Supabase SQL Editor to set up the entire database.

-- 1. Create Tables
-- Category
CREATE TABLE IF NOT EXISTS "Category" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL
);

-- UnitOfMeasure
CREATE TABLE IF NOT EXISTS "UnitOfMeasure" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  sigla TEXT NOT NULL
);

-- Supplier
CREATE TABLE IF NOT EXISTS "Supplier" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cnpj TEXT NOT NULL
);

-- Material
CREATE TABLE IF NOT EXISTS "Material" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  "categoriaId" BIGINT REFERENCES "Category"(id),
  "unidadeMedidaId" BIGINT REFERENCES "UnitOfMeasure"(id),
  "fornecedorId" BIGINT REFERENCES "Supplier"(id),
  tipo_material TEXT NOT NULL,
  referencia TEXT,
  estoque_inicial NUMERIC DEFAULT 0,
  estoque_minimo NUMERIC DEFAULT 0,
  valor_unitario NUMERIC DEFAULT 0,
  localizacao_fisica TEXT,
  estoque_atual NUMERIC DEFAULT 0,
  percentual_venda NUMERIC DEFAULT 0,
  preco_venda NUMERIC DEFAULT 0
);

-- Patient
CREATE TABLE IF NOT EXISTS "Patient" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  cpf TEXT,
  email TEXT,
  telefone TEXT
);

-- Course
CREATE TABLE IF NOT EXISTS "Course" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  descricao TEXT
);

-- Movimentacao
CREATE TABLE IF NOT EXISTS "Movimentacao" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data DATE NOT NULL DEFAULT CURRENT_DATE,
  material_id BIGINT REFERENCES "Material"(id),
  quantidade NUMERIC NOT NULL,
  valor_unitario NUMERIC NOT NULL,
  valor_total NUMERIC NOT NULL,
  tipo TEXT NOT NULL CHECK (tipo IN ('ENTRADA', 'SAIDA')),
  tipo_entrada TEXT,
  paciente_ou_curso TEXT,
  "patientId" BIGINT REFERENCES "Patient"(id),
  "courseId" BIGINT REFERENCES "Course"(id),
  profissional_responsavel TEXT,
  observacoes TEXT
);

-- Setting
CREATE TABLE IF NOT EXISTS "Setting" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT NOT NULL
);

-- Perfil
CREATE TABLE IF NOT EXISTS "Perfil" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  descricao TEXT,
  status TEXT NOT NULL DEFAULT 'Ativo',
  permissions JSONB NOT NULL DEFAULT '{
    "dashboard": {"visualizar": true, "criar": false, "editar": false, "excluir": false},
    "movimentacoes": {"visualizar": true, "criar": true, "editar": true, "excluir": true},
    "estoque": {"visualizar": true, "criar": true, "editar": true, "excluir": true},
    "pacientes": {"visualizar": true, "criar": true, "editar": true, "excluir": true},
    "cursos": {"visualizar": true, "criar": true, "editar": true, "excluir": true},
    "relatorios": {"visualizar": true, "criar": true, "editar": true, "excluir": true},
    "usuarios": {"visualizar": true, "criar": true, "editar": true, "excluir": true},
    "configuracoes": {"visualizar": true, "criar": true, "editar": true, "excluir": true}
  }'
);

-- users (Profile table)
CREATE TABLE IF NOT EXISTS "users" (
  id UUID PRIMARY KEY REFERENCES auth.users(id),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'OPERADOR',
  perfil_id BIGINT REFERENCES "Perfil"(id)
);

-- 2. Enable RLS on all tables
ALTER TABLE "Material" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UnitOfMeasure" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Supplier" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Patient" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Course" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Movimentacao" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Setting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Perfil" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies for all tables (Allow all for authenticated users)
-- Perfil
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Perfil";
CREATE POLICY "Allow all for authenticated" ON "Perfil" FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- Material
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Material";
CREATE POLICY "Allow all for authenticated" ON "Material" FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Category
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Category";
CREATE POLICY "Allow all for authenticated" ON "Category" FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- UnitOfMeasure
DROP POLICY IF EXISTS "Allow all for authenticated" ON "UnitOfMeasure";
CREATE POLICY "Allow all for authenticated" ON "UnitOfMeasure" FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Supplier
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Supplier";
CREATE POLICY "Allow all for authenticated" ON "Supplier" FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Patient
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Patient";
CREATE POLICY "Allow all for authenticated" ON "Patient" FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Course
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Course";
CREATE POLICY "Allow all for authenticated" ON "Course" FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Movimentacao
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Movimentacao";
CREATE POLICY "Allow all for authenticated" ON "Movimentacao" FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Setting
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Setting";
CREATE POLICY "Allow all for authenticated" ON "Setting" FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- users
DROP POLICY IF EXISTS "Allow all for authenticated" ON "users";
CREATE POLICY "Allow all for authenticated" ON "users" FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 4. Reload PostgREST schema cache
NOTIFY pgrst, 'reload schema';
