-- SQL Script to fix RLS (Row Level Security) policies
-- Run this in your Supabase SQL Editor to allow authenticated users to perform CRUD operations.

-- 1. Enable RLS on all tables (if not already enabled)
ALTER TABLE "Material" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UnitOfMeasure" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Supplier" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Patient" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Course" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Movimentacao" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Setting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;

-- 2. Create Policies for "Material"
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Material";
CREATE POLICY "Allow all for authenticated" ON "Material"
FOR ALL TO authenticated
USING (true)
WITH CHECK (true);

-- 3. Create Policies for "Category"
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Category";
CREATE POLICY "Allow all for authenticated" ON "Category"
FOR ALL TO authenticated
USING (true)
WITH CHECK (true);

-- 4. Create Policies for "UnitOfMeasure"
DROP POLICY IF EXISTS "Allow all for authenticated" ON "UnitOfMeasure";
CREATE POLICY "Allow all for authenticated" ON "UnitOfMeasure"
FOR ALL TO authenticated
USING (true)
WITH CHECK (true);

-- 5. Create Policies for "Supplier"
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Supplier";
CREATE POLICY "Allow all for authenticated" ON "Supplier"
FOR ALL TO authenticated
USING (true)
WITH CHECK (true);

-- 6. Create Policies for "Patient"
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Patient";
CREATE POLICY "Allow all for authenticated" ON "Patient"
FOR ALL TO authenticated
USING (true)
WITH CHECK (true);

-- 7. Create Policies for "Course"
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Course";
CREATE POLICY "Allow all for authenticated" ON "Course"
FOR ALL TO authenticated
USING (true)
WITH CHECK (true);

-- 8. Create Policies for "Movimentacao"
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Movimentacao";
CREATE POLICY "Allow all for authenticated" ON "Movimentacao"
FOR ALL TO authenticated
USING (true)
WITH CHECK (true);

-- 9. Create Policies for "Setting"
DROP POLICY IF EXISTS "Allow all for authenticated" ON "Setting";
CREATE POLICY "Allow all for authenticated" ON "Setting"
FOR ALL TO authenticated
USING (true)
WITH CHECK (true);

-- 10. Create Policies for "users"
DROP POLICY IF EXISTS "Allow all for authenticated" ON "users";
CREATE POLICY "Allow all for authenticated" ON "users"
FOR ALL TO authenticated
USING (true)
WITH CHECK (true);

-- 11. Create Policies for "User"
DROP POLICY IF EXISTS "Allow all for authenticated" ON "User";
CREATE POLICY "Allow all for authenticated" ON "User"
FOR ALL TO authenticated
USING (true)
WITH CHECK (true);

-- 12. Ensure ID columns are auto-incrementing (Identity)
-- Note: Run these only if you see errors about missing IDs during insert
-- ALTER TABLE "Material" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- ALTER TABLE "Category" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- ALTER TABLE "UnitOfMeasure" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- ALTER TABLE "Supplier" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- ALTER TABLE "Patient" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- ALTER TABLE "Course" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- ALTER TABLE "Movimentacao" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 13. Reload PostgREST schema cache
NOTIFY pgrst, 'reload schema';
